# ===================================================================
# P R O D U C T I O N - P R O F I L E - S E T T I NGS (For PostgreSQL)
# ===================================================================

# Render 환경 변수에 설정된 값을 사용하도록 지시
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# PostgreSQL 드라이버 및 Dialect 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect